# Generated by Django 4.2.4 on 2023-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquary',
            new_name='Enquiry',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='emailadd',
            new_name='emailaddress',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquarydate',
            new_name='enquirydate',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquarytext',
            new_name='enquirytext',
        ),
    ]
